### ISSUE TITLE
[FEATURE] Frontend UI guide

### ISSUE THREAD

**Issue by danifara3** [BuildForSDGCohort2/Team-030-Frontend#2]
please let get this front end going 

some features i thought of;
1) farmer registration
2) consumer registration
    - retailer
    - final consumer
3) sponsors or financial investors registration
4) blogs
5)testimony
6) rating and recommendations
7) to spice things up: registration of truck or lorry drivers to help dispatch goods/ farm produce to retailers

Now after successful registration into the site portal

1) farmers features:
a) addition of GPS/MAPPING system to register farms
b) adding of photo/camera privilege to snap farm produce while on farm and/or after harvest
c) chatting and broadcasting {here the chatting is necessary for further info or detail gathering between the farmer and consumers or investors}

There are lots of ideas but i think we all need to start contributing. i could see some groups already have something up and running. Please  All hands on deck now. We've got Pros amongst us which i know and believe. after seeing the list of features... we will know if we stick to frameworks or not

**Comment by jan-far** [comment]
Thanks. Wanted us to deliberate on it during the online session. So that we may know what and what to include as an issue. Will proceed with the milestones

**Comment by kingsley-einstein** [comment]
We would be needing a UI design or guide to follow. I might have to look at an example and come up with a design. Someone else should likewise take it upon themselves to come up with a design.

With that said, I'm thinking a guest would have to first register as a regular user. On arriving the sign up page, they fill in the necessary (first name, last name, email and all) and hit the submit button, it takes them to another page where they get to select whether they're a farmer, a merchant or retailer, a buyer (consumer), a warehousing agent or an investor/company and fill in information pertaining to their choice (for example, a farmer gets to input their farm location e.t.c.)

**Comment by jan-far** [comment]
Not bad at all. It's logical. I already started thinking on something. It's a delay somewhat. But with you guys skills, i believe we will get it done in no time after having a UI design.
It's a nice thing, that means it will keep the records somewhat and definitely update the user role/category after choosing who they are.

This should mean that, after successfully registering, you become a user but not under a category. Which the next page is going to be about choosing where the user belongs. Fine!
Now, what i have in mind is this? In case when the user just closed the tab or discontinued the registration. Can we get the user back there (the category page) to make sure they pick and belong to a stand? 
Also, a consumer who wish to change plan, from consumer to retailer, let's try see if that can be done. 
For now... We need your idea implemented and worked upon. Thanks guys. Will work on UI design and see if i can come up with something

**Comment by jan-far** [comment]
Now lets get into new issues for UI sprint 3
